import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the tooltip slice
const initialState = {
    openTooltip: null,
};

// Define the tooltip slice using Redux Toolkit's createSlice function
const tooltipSlice = createSlice({
    name: "tooltip",
    initialState,
    reducers: {
        // The reducer for opening the tooltip
        // It sets openTooltip to the payload of the action
        openTooltip: (state, action) => {
            state.openTooltip = action.payload;
        },
        closeTooltip: (state) => {
            state.openTooltip = null;
        },
    },
});

// Export the action creators generated by createSlice
export const { openTooltip, closeTooltip } = tooltipSlice.actions;
// Export the reducer generated by createSlice
export default tooltipSlice.reducer;
